version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-extension"
s3_prefix = "aws-lambda-extension"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
